# -*- coding: utf-8 -*-
"""Day1_Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m01sJzLsZ09_YIOWxav1Op0po2HUoaB5
"""

a=50
print(a)

a,b =10,20
print("a is 10 and 20 is b")
print(f"10 is a and 20 is b" )
print(f"a is {a} but b is {b}")

5//2

#find number is poitive or negative or zero
num=int(input("Enter number"))
if num<0:
  print(f"{num} is negative")
elif num==0:
  print(f"{num} is zero")
else:
  print(f"{num} is postiive")

#read perc and print passing class
pert=float(input("Enter the percentage:"))
if pert>=60:
  print("The student is passed in First Class!")
elif pert>=50 and pert<=60:
  print("The student is passed in Second Class!")
elif pert>=40 and pert<=50:
  print("The student is passed in Third Class!")
else:
  print("The student is Failed!")

score=int(input("Enter the score:"))
if 90<=score:
  print("Grade is Outstanding!")
elif 75<=score:
  print("Grade is Excellent!")
elif 60<=score:
  print("Grade is Good!")
elif 40<=score:
  print("Grade is Average!")
else:
  print("Grade is Poor!")

#Swap contains two variables.
a,b=10,20
print(f"a:{a} and b:{b}")
a,b=b,a
print(f"a:{a} and b:{b}")

#read boolean false from user
data=bool(input("Enter:"))
print(f"data is {data}")

#accepting multiple inputs
dd,mm,yy=map(int,input("Enter the date:dd,mm,yy").split("/"))
print(f"day:{dd}\n month:{mm} \n year:{yy}")

a,b,c=map(float,input("Enter the three numbers:").split(","))
d=(b**2)-(4*a*c)
if d>=0:
  e=(-b+(d)**0.5)/(2*a)
  f=(-b-(d)**0.5)/(2*a)
  print(f"The root are {e} and {f}")
else:
  print("Imaginary roots")

#print 10,20,30...100 using loop
for i in range(10,101,10):
  print(i)

#print numbers only perfectly divisible by 3,range 1 to 50
for i in range(1,51):
  if i%3==0:
    print(i,end=", ") #by default end is /n

#another method is using for in range(1,51,3) will return same

#print numbers only perfectly divisible by 3 and 5,range 1 to 50
for i in range(1,101):
  if i%3==0 and i%5==0:
    print(i,end=", ")

#for to print factorial of given number
n=4
product=1
for i in range(1,n+1,1):
    product*=i
print(f"{n} factorial is:{product}")

#print the table of 3
m=int(input("Enter the number:"))
for i in range(1,11,1):
  print(f"{m}X{i}={m*i}")

#for --- range(start,end,step)
#start if not given --> 0
#step if not given--> +1
for i in range(4):
  print(i)

for i in range(6,0,-1):
  print("X"*i)

for i in range(6,0,-1):
  print(" "*(6-i),"X "*i)

#Diamond problem
for i in range(1,7,1):
  print(" "*(6-i),"X "*i)
for i in range(5,0,-1):
  print(" "*(6-i),"X "*i)