# -*- coding: utf-8 -*-
"""Day_2_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ma_KHYQho3C7vtMimXP9F_t6UkHPv7fS
"""

#reverse number
n=int(input("Enter the number:"))
rno=0

while n>0:
  digit=n%10        #123 3   12 2        1
  rno=rno*10+digit  #0*10+3  3*10+2=32   32*10+1 321
  n=n//10           #12      1           0
print(rno)

#palindrone or not
n=int(input("Enter the number:"))
temp=n
rno=0
while temp>0:
  digit=temp%10
  rno=rno*10+digit
  temp=temp//10
if n==rno:
  print("Palindrome")
else:
  print("not")

#print armstring no from 0 to 100
n=int(input("Enter number:"))
temp==n
ano=0
while temp>0:
  digit=temp%10
  ano=ano+digit**3
  temp=temp//10
if n==ano:
  print("A")
else:
  print("N")

#Check whether the given number is prime or not.
#flag concept: flag=true---if something goes wrong false
number=int(input("Enter a number:"))#6
flag=True
for i in range(2,number):
    print(f"div by {i}")
    if number%i==0:
        flag=False
        break
if flag:#if flag==True
    print(f"{number} is prime")
else:
    print(f"{number} is not prime")

#print all prime no from 100-1000
#number=int(input("Enter a number:"))#6


for number in range(100,1001):
  flag=True
  for i in range(2,number):
    if number%i==0:
      flag=False
      break
  if flag:#if flag==True
    print(f"{number} is prime")

#perfect number
number=int(input("Enter a number:"))
sum=0
for i in range(1,number):
    if number%i==0:
        sum+=i
if sum==number:
    print(f"{number} is perfect number")
else:
    print(f"{number} is not perfect number")

#menu driven
"""Use above code to implement a billing system where the user would enter:
- Number of teas
- Number of coffees
- Number of waters
- Number of bun muskas
Calculate total bill amount to be paid and bill should only display items which are ordered. Also, tea is 10 rupees, coffee is 40 rupees, water is 20 rupees, and bun maska is 100."""


while True:
    #menu
    print("Apna Tea Stall")
    print("--------------")
    print("1.Tea")
    print("2.Coffee")
    print("3.Water")
    print("4.Bun Maska")
    print("0.Exit")
    print("--------------")
    choice=int(input("Enter:"))
    if choice==1:
        print("tea selected:")
    elif choice==2:
        print("coffee selected:")
    elif choice==3:
        print("water selected:")
    elif choice==4:
        print("bun maska selected:")
    elif choice==0:
        print("Thanks for visit")
        break#stops the loop
    else:#default
        print("Please check the option.")

#menu driven
"""Use above code to implement a billing system where the user would enter:
- Number of teas
- Number of coffees
- Number of waters
- Number of bun muskas
Calculate total bill amount to be paid and bill should only display items which are ordered. Also, tea is 10 rupees, coffee is 40 rupees, water is 20 rupees, and bun maska is 100."""

tea_cost,coffee_cost,water_cost,bm_cost=10.00,40.00,20.00,100.00
tea_qty=coffee_qty=water_qty=bm_qty=0
while True:
    #menu
    print("Apna Tea Stall")
    print("--------------")
    print("1.Tea")
    print("2.Coffee")
    print("3.Water")
    print("4.Bun Maska")
    print("0.Exit")
    print("--------------")
    choice=int(input("Enter:"))
    if choice==1:
        tea_qty+=int(input("tea selected enter quantity:"))
    elif choice==2:
        coffee_qty+=int(input("coffee selected enter quantity:"))
    elif choice==3:
        water_qty+=int(input("water selected enter quantity:"))
    elif choice==4:
        bm_qty+=int(input("bun maska selected enter quantity:"))
    elif choice==0:
        print("Thanks for visit")
        break#stops the loop
    else:#default
        print("Please check the option.")
#billing
print(f"-------------------------")
print(f"          Bill           ")
print(f"-------------------------")
print(f"item   qty   cost   total")
if tea_qty!=0:
    print(f"tea    {tea_qty}     {tea_cost}   {tea_qty*tea_cost}")
if coffee_qty!=0:
  print(f"coffee {coffee_qty}     {coffee_cost}   {coffee_qty*coffee_cost}")
if water_qty!=0:
  print(f"Water  {water_qty}     {water_cost}   {water_qty*water_cost}")
if bm_qty!=0:
  print(f"tea    {bm_qty}     {bm_cost}   {bm_qty*bm_cost}")
print(f"-------------------------")
print(f"Total amount to pay: {tea_qty*tea_cost+coffee_qty*coffee_cost+water_qty*water_cost+bm_qty*bm_cost}")

#read word and reverse word pyramid
word=input("Enter the string:")
for i in range(len(word),0,-1):
  print(word[0:i])

#Count vowels in given string.
line=input("Enter a line to test").lower()
count=0
for c in "aeiou":
    print(c,line.count(c))
    count+=line.count(c)
print(f"Total number of vowels are {count}")

print("X")
for space in range(1,6):
    print("X".ljust(space),"X",sep="")
print("".rjust(7,"X"))

print("X")
for space in range(1,6):
    print("X".ljust(space))
print("".rjust(7,"X"))



print("X"*11)

line="this is done by him"
print(line.replace("is","was"))

line="aaaabbbaaaaabbbbbb"
i=j=0
while i<len(line):
  alpha=line[i]
  j=i+1